version: '3'
services:

  sslproxy:
    image: zsoerenm/magento2-sslproxy:2.2.6
    depends_on:
      - web
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./certs/key.pem:/etc/nginx/ssl/nginx.key
      - ./certs/cert.pem:/etc/nginx/ssl/nginx.crt
    environment:
      - BACKEND_HOST=web
      - SERVER_NAME=magento2.test

  # varnish:
  #   image: zsoerenm/magento2-varnish:2.2.6
  #   depends_on:
  #     - web
      

  redis:
    image: redis:alpine

  web:
    image: zsoerenm/magento2-nginx:2.2.6
    depends_on:
      - php
    volumes:
      - mediadata:/var/www/html/pub/media:ro
      - appdata:/var/www/html:ro
#      - ./src/app/code:/var/www/html/app/code:ro
#      - ./src/vendor/<some_vendor>:/var/www/html/vendor/<some_vendor>:ro
    environment:
      - BACKEND_HOST=php
      - SERVER_NAME=web

  php:
    image: zsoerenm/magento2-php:2.2.6
    depends_on:
      - db
    volumes:
      - mediadata:/var/www/html/pub/media
      - configdata:/var/www/html/app/etc
      - appdata:/var/www/html
      - ../co2ok-plugin-magento-2/Milodv:/var/www/html/app/code/Milodv
      # - ../Custom-Fee-Magento2/Sivajik34:/var/www/html/app/code/Sivajik34
      # - ../Donation:/var/www/html/app/code/Donation
#      - ./src/app/code:/var/www/html/app/code
#      - ./src/vendor/<some_vendor>:/var/www/html/vendor/<some_vendor>
    # environment:
      # - DEFAULT_CACHE_REDIS_SERVER=redis
      # - DEFAULT_CACHE_REDIS_DATABASE=1
      # - PAGE_CACHE_REDIS_SERVER=redis
      # - PAGE_CACHE_REDIS_DATABASE=2
      # - SESSION_REDIS_SERVER=redis
      # - SESSION_REDIS_DATABASE=3

  db:
    image: mariadb:10.2
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: 'mysqladmin ping --silent'
    environment:
      - MYSQL_ROOT_PASSWORD=magento2
      - MYSQL_DATABASE=magento2
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento2

  # cron:
  #   image: zsoerenm/magento2-php:2.2.6
  #   depends_on:
  #     - db
  #   volumes:
  #     - mediadata:/var/www/html/pub/media
  #     - configdata:/var/www/html/app/etc
  #     - appdata:/var/www/html
  #   entrypoint: "su magento -s /bin/sh -c 'trap exit TERM; while :; do bin/magento cron:run; sleep 1m & wait $${!}; done;'"

volumes:
  dbdata:
  appdata:
  mediadata:
  configdata:
